# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  #  notion_test client class.
  class Client
    include CoreLibrary
    attr_reader :config, :auth_managers

    def user_agent_detail
      config.user_agent_detail
    end

    # Access to blocks controller.
    # @return [BlocksApi] Returns the controller instance.
    def blocks
      @blocks ||= BlocksApi.new @global_configuration
    end

    # Access to comments controller.
    # @return [CommentsApi] Returns the controller instance.
    def comments
      @comments ||= CommentsApi.new @global_configuration
    end

    # Access to databases controller.
    # @return [DatabasesApi] Returns the controller instance.
    def databases
      @databases ||= DatabasesApi.new @global_configuration
    end

    # Access to pages controller.
    # @return [PagesApi] Returns the controller instance.
    def pages
      @pages ||= PagesApi.new @global_configuration
    end

    # Access to search controller.
    # @return [SearchApi] Returns the controller instance.
    def search
      @search ||= SearchApi.new @global_configuration
    end

    # Access to users controller.
    # @return [UsersApi] Returns the controller instance.
    def users
      @users ||= UsersApi.new @global_configuration
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 30,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524, 408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put get put], http_callback: nil,
      proxy_settings: nil, logging_configuration: nil,
      environment: Environment::PRODUCTION, bearer_auth_credentials: nil,
      config: nil
    )
      @config = if config.nil?
                  Configuration.new(
                    connection: connection, adapter: adapter, timeout: timeout,
                    max_retries: max_retries, retry_interval: retry_interval,
                    backoff_factor: backoff_factor,
                    retry_statuses: retry_statuses,
                    retry_methods: retry_methods, http_callback: http_callback,
                    proxy_settings: proxy_settings,
                    logging_configuration: logging_configuration,
                    environment: environment,
                    bearer_auth_credentials: bearer_auth_credentials
                  )
                else
                  config
                end
      user_agent_params = BaseApi.user_agent_parameters

      @global_configuration = GlobalConfiguration.new(client_configuration: @config)
                                                 .base_uri_executor(@config.method(:get_base_uri))
                                                 .global_errors(BaseApi::GLOBAL_ERRORS)
                                                 .user_agent(BaseApi.user_agent,
                                                             agent_parameters: user_agent_params)

      initialize_auth_managers(@global_configuration)
      @global_configuration = @global_configuration.auth_managers(@auth_managers)
    end

    # Initializes the auth managers hash used for authenticating API calls.
    # @param [GlobalConfiguration] global_config The global configuration of the SDK)
    def initialize_auth_managers(global_config)
      @auth_managers = {}
      http_client_config = global_config.client_configuration
      %w[bearerAuth].each { |auth| @auth_managers[auth] = nil }
      @auth_managers['bearerAuth'] = Oauth2.new(http_client_config.bearer_auth_credentials)
    end

    # Creates a client directly from environment variables.
    def self.from_env(**overrides)
      default_config = Configuration.build_default_config_from_env
      new_config = default_config.clone_with(**overrides)
      new(config: new_config)
    end
  end
end
