# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Styling annotations applied to the text.
  class Annotations < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Whether the text is bold.
    # @return [TrueClass | FalseClass]
    attr_accessor :bold

    # Whether the text is italic.
    # @return [TrueClass | FalseClass]
    attr_accessor :italic

    # Whether the text has a strikethrough.
    # @return [TrueClass | FalseClass]
    attr_accessor :strikethrough

    # Whether the text is underlined.
    # @return [TrueClass | FalseClass]
    attr_accessor :underline

    # Whether the text is formatted as inline code.
    # @return [TrueClass | FalseClass]
    attr_accessor :code

    # The color of the text. Possible values include default, gray, brown,
    # orange, yellow, green, blue, purple, pink, red, and their background
    # variants (e.g., gray_background).
    # @return [String]
    attr_accessor :color

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bold'] = 'bold'
      @_hash['italic'] = 'italic'
      @_hash['strikethrough'] = 'strikethrough'
      @_hash['underline'] = 'underline'
      @_hash['code'] = 'code'
      @_hash['color'] = 'color'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        bold
        italic
        strikethrough
        underline
        code
        color
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(bold: SKIP, italic: SKIP, strikethrough: SKIP,
                   underline: SKIP, code: SKIP, color: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @bold = bold unless bold == SKIP
      @italic = italic unless italic == SKIP
      @strikethrough = strikethrough unless strikethrough == SKIP
      @underline = underline unless underline == SKIP
      @code = code unless code == SKIP
      @color = color unless color == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      bold = hash.key?('bold') ? hash['bold'] : SKIP
      italic = hash.key?('italic') ? hash['italic'] : SKIP
      strikethrough = hash.key?('strikethrough') ? hash['strikethrough'] : SKIP
      underline = hash.key?('underline') ? hash['underline'] : SKIP
      code = hash.key?('code') ? hash['code'] : SKIP
      color = hash.key?('color') ? hash['color'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Annotations.new(bold: bold,
                      italic: italic,
                      strikethrough: strikethrough,
                      underline: underline,
                      code: code,
                      color: color,
                      additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Annotations | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} bold: #{@bold}, italic: #{@italic}, strikethrough: #{@strikethrough},"\
      " underline: #{@underline}, code: #{@code}, color: #{@color}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} bold: #{@bold.inspect}, italic: #{@italic.inspect}, strikethrough:"\
      " #{@strikethrough.inspect}, underline: #{@underline.inspect}, code: #{@code.inspect},"\
      " color: #{@color.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
