# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Block type-specific content to update. Include the block type key with the
  # fields to modify.
  class BlocksRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Set to true to archive the block.
    # @return [TrueClass | FalseClass]
    attr_accessor :archived

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['archived'] = 'archived'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        archived
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(archived: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @archived = archived unless archived == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      archived = hash.key?('archived') ? hash['archived'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      BlocksRequest.new(archived: archived,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} archived: #{@archived}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} archived: #{@archived.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
