# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # BlocksChildrenRequest Model.
  class BlocksChildrenRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Array of block objects to append as children. Maximum 100 blocks per
    # request.
    # @return [Array[Block]]
    attr_accessor :children

    # The ID of an existing block to insert the new children after. If omitted,
    # blocks are appended to the end.
    # @return [UUID | String]
    attr_accessor :after

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['children'] = 'children'
      @_hash['after'] = 'after'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        after
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(children:, after: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @children = children
      @after = after unless after == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      children = nil
      unless hash['children'].nil?
        children = []
        hash['children'].each do |structure|
          children << (Block.from_hash(structure) if structure)
        end
      end

      children = nil unless hash.key?('children')
      after = hash.key?('after') ? hash['after'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      BlocksChildrenRequest.new(children: children,
                                after: after,
                                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} children: #{@children}, after: #{@after}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} children: #{@children.inspect}, after: #{@after.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
