# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module NotionTest
  # A Block object represents a piece of content within a Notion page. Blocks
  # are the building blocks of all page content and can be of many types
  # including paragraphs, headings, lists, images, code, tables, and more.
  # Blocks can contain other blocks as children, forming a tree structure.
  class Block < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "block" for block objects.
    # @return [Object1]
    attr_accessor :object

    # Unique identifier for the block.
    # @return [UUID | String]
    attr_accessor :id

    # A Parent object represents the parent of a page, database, or block. The
    # parent can be a workspace, page, database, or block.
    # @return [Parent]
    attr_accessor :parent

    # The type of block. Determines which type-specific content field is
    # present. Common types include paragraph, heading_1, heading_2, heading_3,
    # bulleted_list_item, numbered_list_item, to_do, toggle, code, image,
    # divider, table, and many more.
    # @return [Type1]
    attr_accessor :type

    # Date and time when the block was created (ISO 8601).
    # @return [DateTime]
    attr_accessor :created_time

    # Date and time when the block was last edited (ISO 8601).
    # @return [DateTime]
    attr_accessor :last_edited_time

    # A partial User object containing only the object type and ID. Used in
    # created_by and last_edited_by fields.
    # @return [PartialUser]
    attr_accessor :created_by

    # A partial User object containing only the object type and ID. Used in
    # created_by and last_edited_by fields.
    # @return [PartialUser]
    attr_accessor :last_edited_by

    # Whether the block has been archived.
    # @return [TrueClass | FalseClass]
    attr_accessor :archived

    # Whether the block is in the trash.
    # @return [TrueClass | FalseClass]
    attr_accessor :in_trash

    # Whether the block has child blocks nested within it.
    # @return [TrueClass | FalseClass]
    attr_accessor :has_children

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['object'] = 'object'
      @_hash['id'] = 'id'
      @_hash['parent'] = 'parent'
      @_hash['type'] = 'type'
      @_hash['created_time'] = 'created_time'
      @_hash['last_edited_time'] = 'last_edited_time'
      @_hash['created_by'] = 'created_by'
      @_hash['last_edited_by'] = 'last_edited_by'
      @_hash['archived'] = 'archived'
      @_hash['in_trash'] = 'in_trash'
      @_hash['has_children'] = 'has_children'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        parent
        created_by
        last_edited_by
        archived
        in_trash
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(object:, id:, type:, created_time:, last_edited_time:,
                   has_children:, parent: SKIP, created_by: SKIP,
                   last_edited_by: SKIP, archived: SKIP, in_trash: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @object = object
      @id = id
      @parent = parent unless parent == SKIP
      @type = type
      @created_time = created_time
      @last_edited_time = last_edited_time
      @created_by = created_by unless created_by == SKIP
      @last_edited_by = last_edited_by unless last_edited_by == SKIP
      @archived = archived unless archived == SKIP
      @in_trash = in_trash unless in_trash == SKIP
      @has_children = has_children
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      object = hash.key?('object') ? hash['object'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      created_time = if hash.key?('created_time')
                       (DateTimeHelper.from_rfc3339(hash['created_time']) if hash['created_time'])
                     end
      last_edited_time = if hash.key?('last_edited_time')
                           (DateTimeHelper.from_rfc3339(hash['last_edited_time']) if hash['last_edited_time'])
                         end
      has_children = hash.key?('has_children') ? hash['has_children'] : nil
      parent = Parent.from_hash(hash['parent']) if hash['parent']
      created_by = PartialUser.from_hash(hash['created_by']) if hash['created_by']
      last_edited_by = PartialUser.from_hash(hash['last_edited_by']) if hash['last_edited_by']
      archived = hash.key?('archived') ? hash['archived'] : SKIP
      in_trash = hash.key?('in_trash') ? hash['in_trash'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Block.new(object: object,
                id: id,
                type: type,
                created_time: created_time,
                last_edited_time: last_edited_time,
                has_children: has_children,
                parent: parent,
                created_by: created_by,
                last_edited_by: last_edited_by,
                archived: archived,
                in_trash: in_trash,
                additional_properties: additional_properties)
    end

    def to_custom_created_time
      DateTimeHelper.to_rfc3339(created_time)
    end

    def to_custom_last_edited_time
      DateTimeHelper.to_rfc3339(last_edited_time)
    end

    # Validates an instance of the object from a given value.
    # @param [Block | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.object,
                                ->(val) { Object1.validate(val) }) and
            APIHelper.valid_type?(value.id,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.type,
                                  ->(val) { Type1.validate(val) }) and
            APIHelper.valid_type?(value.created_time,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.last_edited_time,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.has_children,
                                  ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['object'],
                              ->(val) { Object1.validate(val) }) and
          APIHelper.valid_type?(value['id'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['type'],
                                ->(val) { Type1.validate(val) }) and
          APIHelper.valid_type?(value['created_time'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['last_edited_time'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['has_children'],
                                ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, id: #{@id}, parent: #{@parent}, type: #{@type},"\
      " created_time: #{@created_time}, last_edited_time: #{@last_edited_time}, created_by:"\
      " #{@created_by}, last_edited_by: #{@last_edited_by}, archived: #{@archived}, in_trash:"\
      " #{@in_trash}, has_children: #{@has_children}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, id: #{@id.inspect}, parent: #{@parent.inspect},"\
      " type: #{@type.inspect}, created_time: #{@created_time.inspect}, last_edited_time:"\
      " #{@last_edited_time.inspect}, created_by: #{@created_by.inspect}, last_edited_by:"\
      " #{@last_edited_by.inspect}, archived: #{@archived.inspect}, in_trash:"\
      " #{@in_trash.inspect}, has_children: #{@has_children.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
