# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Bot-specific information. Only present when type is "bot".
  class Bot < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Information about the bot's owner.
    # @return [Owner]
    attr_accessor :owner

    # The name of the workspace the bot belongs to.
    # @return [String]
    attr_accessor :workspace_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['owner'] = 'owner'
      @_hash['workspace_name'] = 'workspace_name'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        owner
        workspace_name
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        workspace_name
      ]
    end

    def initialize(owner: SKIP, workspace_name: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @owner = owner unless owner == SKIP
      @workspace_name = workspace_name unless workspace_name == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      owner = Owner.from_hash(hash['owner']) if hash['owner']
      workspace_name =
        hash.key?('workspace_name') ? hash['workspace_name'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Bot.new(owner: owner,
              workspace_name: workspace_name,
              additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} owner: #{@owner}, workspace_name: #{@workspace_name},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} owner: #{@owner.inspect}, workspace_name: #{@workspace_name.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
