# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # CommentsRequest Model.
  class CommentsRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The parent page to create the comment on. Required if discussion_id is not
    # provided.
    # @return [Parent11]
    attr_accessor :parent

    # The ID of an existing discussion thread to add the comment to. Required if
    # parent is not provided.
    # @return [UUID | String]
    attr_accessor :discussion_id

    # Rich text content of the comment.
    # @return [Array[RichText]]
    attr_accessor :rich_text

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['parent'] = 'parent'
      @_hash['discussion_id'] = 'discussion_id'
      @_hash['rich_text'] = 'rich_text'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        parent
        discussion_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(rich_text:, parent: SKIP, discussion_id: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @parent = parent unless parent == SKIP
      @discussion_id = discussion_id unless discussion_id == SKIP
      @rich_text = rich_text
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      rich_text = nil
      unless hash['rich_text'].nil?
        rich_text = []
        hash['rich_text'].each do |structure|
          rich_text << (RichText.from_hash(structure) if structure)
        end
      end

      rich_text = nil unless hash.key?('rich_text')
      parent = Parent11.from_hash(hash['parent']) if hash['parent']
      discussion_id = hash.key?('discussion_id') ? hash['discussion_id'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      CommentsRequest.new(rich_text: rich_text,
                          parent: parent,
                          discussion_id: discussion_id,
                          additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} parent: #{@parent}, discussion_id: #{@discussion_id}, rich_text:"\
      " #{@rich_text}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} parent: #{@parent.inspect}, discussion_id: #{@discussion_id.inspect},"\
      " rich_text: #{@rich_text.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
