# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module NotionTest
  # A Comment object represents a comment on a Notion page or block. Comments
  # contain rich text content and are associated with discussion threads.
  class Comment < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "comment" for comment objects.
    # @return [Object11]
    attr_accessor :object

    # Unique identifier for the comment.
    # @return [UUID | String]
    attr_accessor :id

    # The parent page or block the comment belongs to.
    # @return [Parent1]
    attr_accessor :parent

    # The ID of the discussion thread the comment belongs to.
    # @return [UUID | String]
    attr_accessor :discussion_id

    # Date and time when the comment was created (ISO 8601).
    # @return [DateTime]
    attr_accessor :created_time

    # Date and time when the comment was last edited (ISO 8601).
    # @return [DateTime]
    attr_accessor :last_edited_time

    # A partial User object containing only the object type and ID. Used in
    # created_by and last_edited_by fields.
    # @return [PartialUser]
    attr_accessor :created_by

    # Rich text content of the comment.
    # @return [Array[RichText]]
    attr_accessor :rich_text

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['object'] = 'object'
      @_hash['id'] = 'id'
      @_hash['parent'] = 'parent'
      @_hash['discussion_id'] = 'discussion_id'
      @_hash['created_time'] = 'created_time'
      @_hash['last_edited_time'] = 'last_edited_time'
      @_hash['created_by'] = 'created_by'
      @_hash['rich_text'] = 'rich_text'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(object:, id:, parent:, discussion_id:, created_time:,
                   last_edited_time:, created_by:, rich_text:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @object = object
      @id = id
      @parent = parent
      @discussion_id = discussion_id
      @created_time = created_time
      @last_edited_time = last_edited_time
      @created_by = created_by
      @rich_text = rich_text
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      object = hash.key?('object') ? hash['object'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      parent = Parent1.from_hash(hash['parent']) if hash['parent']
      discussion_id = hash.key?('discussion_id') ? hash['discussion_id'] : nil
      created_time = if hash.key?('created_time')
                       (DateTimeHelper.from_rfc3339(hash['created_time']) if hash['created_time'])
                     end
      last_edited_time = if hash.key?('last_edited_time')
                           (DateTimeHelper.from_rfc3339(hash['last_edited_time']) if hash['last_edited_time'])
                         end
      created_by = PartialUser.from_hash(hash['created_by']) if hash['created_by']
      # Parameter is an array, so we need to iterate through it
      rich_text = nil
      unless hash['rich_text'].nil?
        rich_text = []
        hash['rich_text'].each do |structure|
          rich_text << (RichText.from_hash(structure) if structure)
        end
      end

      rich_text = nil unless hash.key?('rich_text')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Comment.new(object: object,
                  id: id,
                  parent: parent,
                  discussion_id: discussion_id,
                  created_time: created_time,
                  last_edited_time: last_edited_time,
                  created_by: created_by,
                  rich_text: rich_text,
                  additional_properties: additional_properties)
    end

    def to_custom_created_time
      DateTimeHelper.to_rfc3339(created_time)
    end

    def to_custom_last_edited_time
      DateTimeHelper.to_rfc3339(last_edited_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, id: #{@id}, parent: #{@parent}, discussion_id:"\
      " #{@discussion_id}, created_time: #{@created_time}, last_edited_time: #{@last_edited_time},"\
      " created_by: #{@created_by}, rich_text: #{@rich_text}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, id: #{@id.inspect}, parent: #{@parent.inspect},"\
      " discussion_id: #{@discussion_id.inspect}, created_time: #{@created_time.inspect},"\
      " last_edited_time: #{@last_edited_time.inspect}, created_by: #{@created_by.inspect},"\
      " rich_text: #{@rich_text.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
