# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module NotionTest
  # A Database object represents a database in Notion. Databases are collections
  # of pages that share a common schema of properties. The schema defines the
  # columns and their types that all pages in the database will have.
  class Database < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "database" for database objects.
    # @return [Object12]
    attr_accessor :object

    # Unique identifier for the database.
    # @return [UUID | String]
    attr_accessor :id

    # Date and time when the database was created (ISO 8601).
    # @return [DateTime]
    attr_accessor :created_time

    # Date and time when the database was last edited (ISO 8601).
    # @return [DateTime]
    attr_accessor :last_edited_time

    # A partial User object containing only the object type and ID. Used in
    # created_by and last_edited_by fields.
    # @return [PartialUser]
    attr_accessor :created_by

    # A partial User object containing only the object type and ID. Used in
    # created_by and last_edited_by fields.
    # @return [PartialUser]
    attr_accessor :last_edited_by

    # Title of the database as rich text.
    # @return [Array[RichText]]
    attr_accessor :title

    # Description of the database as rich text.
    # @return [Array[RichText]]
    attr_accessor :description

    # Database icon, either an emoji or file.
    # @return [Object]
    attr_accessor :icon

    # Database cover image.
    # @return [File]
    attr_accessor :cover

    # Schema of database properties. Keys are property names, values are
    # property schema objects defining the type and configuration of each
    # column.
    # @return [Hash[String, PropertySchema]]
    attr_accessor :properties

    # A Parent object represents the parent of a page, database, or block. The
    # parent can be a workspace, page, database, or block.
    # @return [Parent]
    attr_accessor :parent

    # The URL of the database in Notion.
    # @return [String]
    attr_accessor :url

    # The public URL of the database, if published to the web. Otherwise null.
    # @return [String]
    attr_accessor :public_url

    # Whether the database has been archived.
    # @return [TrueClass | FalseClass]
    attr_accessor :archived

    # Whether the database is in the trash.
    # @return [TrueClass | FalseClass]
    attr_accessor :in_trash

    # Whether the database is inline (appears within its parent page rather than
    # as a full page).
    # @return [TrueClass | FalseClass]
    attr_accessor :is_inline

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['object'] = 'object'
      @_hash['id'] = 'id'
      @_hash['created_time'] = 'created_time'
      @_hash['last_edited_time'] = 'last_edited_time'
      @_hash['created_by'] = 'created_by'
      @_hash['last_edited_by'] = 'last_edited_by'
      @_hash['title'] = 'title'
      @_hash['description'] = 'description'
      @_hash['icon'] = 'icon'
      @_hash['cover'] = 'cover'
      @_hash['properties'] = 'properties'
      @_hash['parent'] = 'parent'
      @_hash['url'] = 'url'
      @_hash['public_url'] = 'public_url'
      @_hash['archived'] = 'archived'
      @_hash['in_trash'] = 'in_trash'
      @_hash['is_inline'] = 'is_inline'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        icon
        cover
        public_url
        in_trash
        is_inline
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        icon
        cover
        public_url
      ]
    end

    def initialize(object:, id:, created_time:, last_edited_time:, created_by:,
                   last_edited_by:, title:, description:, properties:, parent:,
                   url:, archived:, icon: SKIP, cover: SKIP, public_url: SKIP,
                   in_trash: SKIP, is_inline: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @object = object
      @id = id
      @created_time = created_time
      @last_edited_time = last_edited_time
      @created_by = created_by
      @last_edited_by = last_edited_by
      @title = title
      @description = description
      @icon = icon unless icon == SKIP
      @cover = cover unless cover == SKIP
      @properties = properties
      @parent = parent
      @url = url
      @public_url = public_url unless public_url == SKIP
      @archived = archived
      @in_trash = in_trash unless in_trash == SKIP
      @is_inline = is_inline unless is_inline == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      object = hash.key?('object') ? hash['object'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      created_time = if hash.key?('created_time')
                       (DateTimeHelper.from_rfc3339(hash['created_time']) if hash['created_time'])
                     end
      last_edited_time = if hash.key?('last_edited_time')
                           (DateTimeHelper.from_rfc3339(hash['last_edited_time']) if hash['last_edited_time'])
                         end
      created_by = PartialUser.from_hash(hash['created_by']) if hash['created_by']
      last_edited_by = PartialUser.from_hash(hash['last_edited_by']) if hash['last_edited_by']
      # Parameter is an array, so we need to iterate through it
      title = nil
      unless hash['title'].nil?
        title = []
        hash['title'].each do |structure|
          title << (RichText.from_hash(structure) if structure)
        end
      end

      title = nil unless hash.key?('title')
      # Parameter is an array, so we need to iterate through it
      description = nil
      unless hash['description'].nil?
        description = []
        hash['description'].each do |structure|
          description << (RichText.from_hash(structure) if structure)
        end
      end

      description = nil unless hash.key?('description')
      properties = PropertySchema.from_hash(hash['properties']) if hash['properties']

      properties = nil unless hash.key?('properties')
      parent = Parent.from_hash(hash['parent']) if hash['parent']
      url = hash.key?('url') ? hash['url'] : nil
      archived = hash.key?('archived') ? hash['archived'] : nil
      icon = hash.key?('icon') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:DatabaseIcon), hash['icon']
      ) : SKIP
      cover = File.from_hash(hash['cover']) if hash['cover']
      public_url = hash.key?('public_url') ? hash['public_url'] : SKIP
      in_trash = hash.key?('in_trash') ? hash['in_trash'] : SKIP
      is_inline = hash.key?('is_inline') ? hash['is_inline'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Database.new(object: object,
                   id: id,
                   created_time: created_time,
                   last_edited_time: last_edited_time,
                   created_by: created_by,
                   last_edited_by: last_edited_by,
                   title: title,
                   description: description,
                   properties: properties,
                   parent: parent,
                   url: url,
                   archived: archived,
                   icon: icon,
                   cover: cover,
                   public_url: public_url,
                   in_trash: in_trash,
                   is_inline: is_inline,
                   additional_properties: additional_properties)
    end

    def to_custom_created_time
      DateTimeHelper.to_rfc3339(created_time)
    end

    def to_custom_last_edited_time
      DateTimeHelper.to_rfc3339(last_edited_time)
    end

    # Validates an instance of the object from a given value.
    # @param [Database | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.object,
                                ->(val) { Object12.validate(val) }) and
            APIHelper.valid_type?(value.id,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.created_time,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.last_edited_time,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.created_by,
                                  ->(val) { PartialUser.validate(val) },
                                  is_model_hash: true) and
            APIHelper.valid_type?(value.last_edited_by,
                                  ->(val) { PartialUser.validate(val) },
                                  is_model_hash: true) and
            APIHelper.valid_type?(value.title,
                                  ->(val) { RichText.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.description,
                                  ->(val) { RichText.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.properties,
                                  ->(val) { PropertySchema.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.parent,
                                  ->(val) { Parent.validate(val) },
                                  is_model_hash: true) and
            APIHelper.valid_type?(value.url,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.archived,
                                  ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['object'],
                              ->(val) { Object12.validate(val) }) and
          APIHelper.valid_type?(value['id'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['created_time'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['last_edited_time'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['created_by'],
                                ->(val) { PartialUser.validate(val) },
                                is_model_hash: true) and
          APIHelper.valid_type?(value['last_edited_by'],
                                ->(val) { PartialUser.validate(val) },
                                is_model_hash: true) and
          APIHelper.valid_type?(value['title'],
                                ->(val) { RichText.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['description'],
                                ->(val) { RichText.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['properties'],
                                ->(val) { PropertySchema.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['parent'],
                                ->(val) { Parent.validate(val) },
                                is_model_hash: true) and
          APIHelper.valid_type?(value['url'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['archived'],
                                ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, id: #{@id}, created_time: #{@created_time},"\
      " last_edited_time: #{@last_edited_time}, created_by: #{@created_by}, last_edited_by:"\
      " #{@last_edited_by}, title: #{@title}, description: #{@description}, icon: #{@icon}, cover:"\
      " #{@cover}, properties: #{@properties}, parent: #{@parent}, url: #{@url}, public_url:"\
      " #{@public_url}, archived: #{@archived}, in_trash: #{@in_trash}, is_inline: #{@is_inline},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, id: #{@id.inspect}, created_time:"\
      " #{@created_time.inspect}, last_edited_time: #{@last_edited_time.inspect}, created_by:"\
      " #{@created_by.inspect}, last_edited_by: #{@last_edited_by.inspect}, title:"\
      " #{@title.inspect}, description: #{@description.inspect}, icon: #{@icon.inspect}, cover:"\
      " #{@cover.inspect}, properties: #{@properties.inspect}, parent: #{@parent.inspect}, url:"\
      " #{@url.inspect}, public_url: #{@public_url.inspect}, archived: #{@archived.inspect},"\
      " in_trash: #{@in_trash.inspect}, is_inline: #{@is_inline.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
