# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # DatabasesQueryRequest Model.
  class DatabasesQueryRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Filter conditions to apply. Supports compound filters using and/or as well
    # as property-specific filters.
    # @return [Object]
    attr_accessor :filter

    # Sort conditions to order the results. Multiple sorts can be applied; they
    # are processed in the order provided.
    # @return [Array[Sort]]
    attr_accessor :sorts

    # Pagination cursor from a previous response to continue fetching results.
    # @return [String]
    attr_accessor :start_cursor

    # Maximum number of results to return (max 100).
    # @return [Integer]
    attr_accessor :page_size

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['filter'] = 'filter'
      @_hash['sorts'] = 'sorts'
      @_hash['start_cursor'] = 'start_cursor'
      @_hash['page_size'] = 'page_size'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        filter
        sorts
        start_cursor
        page_size
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(filter: SKIP, sorts: SKIP, start_cursor: SKIP,
                   page_size: 100, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @filter = filter unless filter == SKIP
      @sorts = sorts unless sorts == SKIP
      @start_cursor = start_cursor unless start_cursor == SKIP
      @page_size = page_size unless page_size == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      filter = hash.key?('filter') ? hash['filter'] : SKIP
      # Parameter is an array, so we need to iterate through it
      sorts = nil
      unless hash['sorts'].nil?
        sorts = []
        hash['sorts'].each do |structure|
          sorts << (Sort.from_hash(structure) if structure)
        end
      end

      sorts = SKIP unless hash.key?('sorts')
      start_cursor = hash.key?('start_cursor') ? hash['start_cursor'] : SKIP
      page_size = hash['page_size'] ||= 100

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      DatabasesQueryRequest.new(filter: filter,
                                sorts: sorts,
                                start_cursor: start_cursor,
                                page_size: page_size,
                                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} filter: #{@filter}, sorts: #{@sorts}, start_cursor: #{@start_cursor},"\
      " page_size: #{@page_size}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} filter: #{@filter.inspect}, sorts: #{@sorts.inspect}, start_cursor:"\
      " #{@start_cursor.inspect}, page_size: #{@page_size.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
