# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # DatabasesRequest1 Model.
  class DatabasesRequest1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Updated database title as rich text.
    # @return [Array[RichText]]
    attr_accessor :title

    # Updated database description as rich text.
    # @return [Array[RichText]]
    attr_accessor :description

    # Updated property schema. Include only properties to add or modify. Set a
    # property value to null to remove it.
    # @return [Object]
    attr_accessor :properties

    # Updated database icon.
    # @return [Object]
    attr_accessor :icon

    # Updated database cover image.
    # @return [ExternalFile]
    attr_accessor :cover

    # Whether the database is inline.
    # @return [TrueClass | FalseClass]
    attr_accessor :is_inline

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['title'] = 'title'
      @_hash['description'] = 'description'
      @_hash['properties'] = 'properties'
      @_hash['icon'] = 'icon'
      @_hash['cover'] = 'cover'
      @_hash['is_inline'] = 'is_inline'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        title
        description
        properties
        icon
        cover
        is_inline
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        icon
        cover
      ]
    end

    def initialize(title: SKIP, description: SKIP, properties: SKIP, icon: SKIP,
                   cover: SKIP, is_inline: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @title = title unless title == SKIP
      @description = description unless description == SKIP
      @properties = properties unless properties == SKIP
      @icon = icon unless icon == SKIP
      @cover = cover unless cover == SKIP
      @is_inline = is_inline unless is_inline == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      title = nil
      unless hash['title'].nil?
        title = []
        hash['title'].each do |structure|
          title << (RichText.from_hash(structure) if structure)
        end
      end

      title = SKIP unless hash.key?('title')
      # Parameter is an array, so we need to iterate through it
      description = nil
      unless hash['description'].nil?
        description = []
        hash['description'].each do |structure|
          description << (RichText.from_hash(structure) if structure)
        end
      end

      description = SKIP unless hash.key?('description')
      properties = hash.key?('properties') ? hash['properties'] : SKIP
      icon = hash.key?('icon') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:DatabasesRequest1Icon), hash['icon']
      ) : SKIP
      cover = ExternalFile.from_hash(hash['cover']) if hash['cover']
      is_inline = hash.key?('is_inline') ? hash['is_inline'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      DatabasesRequest1.new(title: title,
                            description: description,
                            properties: properties,
                            icon: icon,
                            cover: cover,
                            is_inline: is_inline,
                            additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [DatabasesRequest1 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} title: #{@title}, description: #{@description}, properties: #{@properties},"\
      " icon: #{@icon}, cover: #{@cover}, is_inline: #{@is_inline}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} title: #{@title.inspect}, description: #{@description.inspect}, properties:"\
      " #{@properties.inspect}, icon: #{@icon.inspect}, cover: #{@cover.inspect}, is_inline:"\
      " #{@is_inline.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
