# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # DatabasesRequest Model.
  class DatabasesRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A Parent object represents the parent of a page, database, or block. The
    # parent can be a workspace, page, database, or block.
    # @return [Parent]
    attr_accessor :parent

    # Rich text array for the database title.
    # @return [Array[RichText]]
    attr_accessor :title

    # Rich text array for the database description.
    # @return [Array[RichText]]
    attr_accessor :description

    # Schema of the database properties. Keys are property names, values are
    # property schema objects defining the type and configuration.
    # @return [Hash[String, PropertySchema]]
    attr_accessor :properties

    # Whether the database appears inline within its parent page rather than as
    # a full page.
    # @return [TrueClass | FalseClass]
    attr_accessor :is_inline

    # Database icon.
    # @return [Object]
    attr_accessor :icon

    # Database cover image.
    # @return [ExternalFile1]
    attr_accessor :cover

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['parent'] = 'parent'
      @_hash['title'] = 'title'
      @_hash['description'] = 'description'
      @_hash['properties'] = 'properties'
      @_hash['is_inline'] = 'is_inline'
      @_hash['icon'] = 'icon'
      @_hash['cover'] = 'cover'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        title
        description
        is_inline
        icon
        cover
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(parent:, properties:, title: SKIP, description: SKIP,
                   is_inline: SKIP, icon: SKIP, cover: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @parent = parent
      @title = title unless title == SKIP
      @description = description unless description == SKIP
      @properties = properties
      @is_inline = is_inline unless is_inline == SKIP
      @icon = icon unless icon == SKIP
      @cover = cover unless cover == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      parent = Parent.from_hash(hash['parent']) if hash['parent']
      properties = PropertySchema.from_hash(hash['properties']) if hash['properties']

      properties = nil unless hash.key?('properties')
      # Parameter is an array, so we need to iterate through it
      title = nil
      unless hash['title'].nil?
        title = []
        hash['title'].each do |structure|
          title << (RichText.from_hash(structure) if structure)
        end
      end

      title = SKIP unless hash.key?('title')
      # Parameter is an array, so we need to iterate through it
      description = nil
      unless hash['description'].nil?
        description = []
        hash['description'].each do |structure|
          description << (RichText.from_hash(structure) if structure)
        end
      end

      description = SKIP unless hash.key?('description')
      is_inline = hash.key?('is_inline') ? hash['is_inline'] : SKIP
      icon = hash.key?('icon') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:DatabasesRequestIcon), hash['icon']
      ) : SKIP
      cover = ExternalFile1.from_hash(hash['cover']) if hash['cover']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      DatabasesRequest.new(parent: parent,
                           properties: properties,
                           title: title,
                           description: description,
                           is_inline: is_inline,
                           icon: icon,
                           cover: cover,
                           additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [DatabasesRequest | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.parent,
                                ->(val) { Parent.validate(val) },
                                is_model_hash: true) and
            APIHelper.valid_type?(value.properties,
                                  ->(val) { PropertySchema.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true)
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['parent'],
                              ->(val) { Parent.validate(val) },
                              is_model_hash: true) and
          APIHelper.valid_type?(value['properties'],
                                ->(val) { PropertySchema.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true)
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} parent: #{@parent}, title: #{@title}, description: #{@description},"\
      " properties: #{@properties}, is_inline: #{@is_inline}, icon: #{@icon}, cover: #{@cover},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} parent: #{@parent.inspect}, title: #{@title.inspect}, description:"\
      " #{@description.inspect}, properties: #{@properties.inspect}, is_inline:"\
      " #{@is_inline.inspect}, icon: #{@icon.inspect}, cover: #{@cover.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
