# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The sort direction.
  class Direction
    DIRECTION = [
      # TODO: Write general description for ASCENDING
      ASCENDING = 'ascending'.freeze,

      # TODO: Write general description for DESCENDING
      DESCENDING = 'descending'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      DIRECTION.include?(value)
    end

    def self.from_value(value, default_value = ASCENDING)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'ascending' then ASCENDING
      when 'descending' then DESCENDING
      else
        default_value
      end
    end
  end
end
