# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # An emoji icon object.
  class Emoji < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "emoji".
    # @return [Type3]
    attr_accessor :type

    # The emoji character.
    # @return [String]
    attr_accessor :emoji

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['emoji'] = 'emoji'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type:, emoji:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type
      @emoji = emoji
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : nil
      emoji = hash.key?('emoji') ? hash['emoji'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Emoji.new(type: type,
                emoji: emoji,
                additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Emoji | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.type,
                                ->(val) { Type3.validate(val) }) and
            APIHelper.valid_type?(value.emoji,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['type'],
                              ->(val) { Type3.validate(val) }) and
          APIHelper.valid_type?(value['emoji'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, emoji: #{@emoji}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, emoji: #{@emoji.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
