# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Equation content in KaTeX format. Present when type is "equation".
  class Equation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The LaTeX equation expression.
    # @return [String]
    attr_accessor :expression

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['expression'] = 'expression'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        expression
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(expression: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @expression = expression unless expression == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      expression = hash.key?('expression') ? hash['expression'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Equation.new(expression: expression,
                   additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Equation | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} expression: #{@expression}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} expression: #{@expression.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
