# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Database cover image.
  class ExternalFile1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "external".
    # @return [Type5]
    attr_accessor :type

    # Always "external".
    # @return [External1]
    attr_accessor :external

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['external'] = 'external'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type:, external:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type
      @external = external
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : nil
      external = External1.from_hash(hash['external']) if hash['external']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ExternalFile1.new(type: type,
                        external: external,
                        additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [ExternalFile1 | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.type,
                                ->(val) { Type5.validate(val) }) and
            APIHelper.valid_type?(value.external,
                                  ->(val) { External1.validate(val) },
                                  is_model_hash: true)
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['type'],
                              ->(val) { Type5.validate(val) }) and
          APIHelper.valid_type?(value['external'],
                                ->(val) { External1.validate(val) },
                                is_model_hash: true)
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, external: #{@external}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, external: #{@external.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
