# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # A File object represents a file in Notion. Files can be either hosted by
  # Notion (type "file") or externally hosted (type "external").
  class File < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The type of file hosting.
    # @return [Type21]
    attr_accessor :type

    # Notion-hosted file details. Present when type is "file". These URLs expire
    # after one hour.
    # @return [File1]
    attr_accessor :file

    # External file details. Present when type is "external".
    # @return [Link]
    attr_accessor :external

    # The name of the file.
    # @return [String]
    attr_accessor :name

    # Caption for the file as rich text.
    # @return [Array[RichText]]
    attr_accessor :caption

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['file'] = 'file'
      @_hash['external'] = 'external'
      @_hash['name'] = 'name'
      @_hash['caption'] = 'caption'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        file
        external
        name
        caption
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type:, file: SKIP, external: SKIP, name: SKIP, caption: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type
      @file = file unless file == SKIP
      @external = external unless external == SKIP
      @name = name unless name == SKIP
      @caption = caption unless caption == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : nil
      file = File1.from_hash(hash['file']) if hash['file']
      external = Link.from_hash(hash['external']) if hash['external']
      name = hash.key?('name') ? hash['name'] : SKIP
      # Parameter is an array, so we need to iterate through it
      caption = nil
      unless hash['caption'].nil?
        caption = []
        hash['caption'].each do |structure|
          caption << (RichText.from_hash(structure) if structure)
        end
      end

      caption = SKIP unless hash.key?('caption')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      File.new(type: type,
               file: file,
               external: external,
               name: name,
               caption: caption,
               additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [File | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.type,
                                     ->(val) { Type21.validate(val) })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['type'],
                            ->(val) { Type21.validate(val) })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, file: #{@file}, external: #{@external}, name: #{@name},"\
      " caption: #{@caption}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, file: #{@file.inspect}, external:"\
      " #{@external.inspect}, name: #{@name.inspect}, caption: #{@caption.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
