# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module NotionTest
  # Notion-hosted file details. Present when type is "file". These URLs expire
  # after one hour.
  class File1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The authenticated S3 URL for the file.
    # @return [String]
    attr_accessor :url

    # The expiration time of the URL.
    # @return [DateTime]
    attr_accessor :expiry_time

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['url'] = 'url'
      @_hash['expiry_time'] = 'expiry_time'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        url
        expiry_time
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(url: SKIP, expiry_time: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @url = url unless url == SKIP
      @expiry_time = expiry_time unless expiry_time == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      url = hash.key?('url') ? hash['url'] : SKIP
      expiry_time = if hash.key?('expiry_time')
                      (DateTimeHelper.from_rfc3339(hash['expiry_time']) if hash['expiry_time'])
                    else
                      SKIP
                    end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      File1.new(url: url,
                expiry_time: expiry_time,
                additional_properties: additional_properties)
    end

    def to_custom_expiry_time
      DateTimeHelper.to_rfc3339(expiry_time)
    end

    # Validates an instance of the object from a given value.
    # @param [File1 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} url: #{@url}, expiry_time: #{@expiry_time}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} url: #{@url.inspect}, expiry_time: #{@expiry_time.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
