# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Filter conditions. Currently only supports filtering by object type (page or
  # database).
  class Filter < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The type of object to filter by.
    # @return [Value]
    attr_accessor :value

    # Must be "object".
    # @return [Property]
    attr_accessor :property

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['value'] = 'value'
      @_hash['property'] = 'property'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        value
        property
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(value: SKIP, property: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @value = value unless value == SKIP
      @property = property unless property == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      value = hash.key?('value') ? hash['value'] : SKIP
      property = hash.key?('property') ? hash['property'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Filter.new(value: value,
                 property: property,
                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} value: #{@value}, property: #{@property}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} value: #{@value.inspect}, property: #{@property.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
