# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "user"., Always "user" for user objects.
  class Object2
    OBJECT2 = [
      # TODO: Write general description for USER
      USER = 'user'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OBJECT2.include?(value)
    end

    def self.from_value(value, default_value = USER)
      return default_value if value.nil?

      default_value
    end
  end
end
