# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "database" for database objects.
  class Object12
    OBJECT12 = [
      # TODO: Write general description for DATABASE
      DATABASE = 'database'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OBJECT12.include?(value)
    end

    def self.from_value(value, default_value = DATABASE)
      return default_value if value.nil?

      default_value
    end
  end
end
