# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "block" for block objects.
  class Object1
    OBJECT1 = [
      # TODO: Write general description for BLOCK
      BLOCK = 'block'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OBJECT1.include?(value)
    end

    def self.from_value(value, default_value = BLOCK)
      return default_value if value.nil?

      default_value
    end
  end
end
