# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "error" for error responses.
  class Object3
    OBJECT3 = [
      # TODO: Write general description for ERROR
      ERROR = 'error'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OBJECT3.include?(value)
    end

    def self.from_value(value, default_value = ERROR)
      return default_value if value.nil?

      default_value
    end
  end
end
