# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "comment" for comment objects.
  class Object11
    OBJECT11 = [
      # TODO: Write general description for COMMENT
      COMMENT = 'comment'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OBJECT11.include?(value)
    end

    def self.from_value(value, default_value = COMMENT)
      return default_value if value.nil?

      default_value
    end
  end
end
