# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "list" for paginated responses.
  class Object
    OBJECT = [
      # TODO: Write general description for LIST
      LIST = 'list'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OBJECT.include?(value)
    end

    def self.from_value(value, default_value = LIST)
      return default_value if value.nil?

      default_value
    end
  end
end
