# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "page" for page objects.
  class Object21
    OBJECT21 = [
      # TODO: Write general description for PAGE
      PAGE = 'page'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OBJECT21.include?(value)
    end

    def self.from_value(value, default_value = PAGE)
      return default_value if value.nil?

      default_value
    end
  end
end
