# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Information about the bot's owner.
  class Owner < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Type12]
    attr_accessor :type

    # Whether the bot is owned by the workspace.
    # @return [TrueClass | FalseClass]
    attr_accessor :workspace

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['workspace'] = 'workspace'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        workspace
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type: SKIP, workspace: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type unless type == SKIP
      @workspace = workspace unless workspace == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP
      workspace = hash.key?('workspace') ? hash['workspace'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Owner.new(type: type,
                workspace: workspace,
                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, workspace: #{@workspace}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, workspace: #{@workspace.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
