# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # PagesRequest Model.
  class PagesRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A Parent object represents the parent of a page, database, or block. The
    # parent can be a workspace, page, database, or block.
    # @return [Parent]
    attr_accessor :parent

    # Property values for the new page. Keys are property names or IDs. If the
    # parent is a database, the values must conform to the database schema.
    # @return [Object]
    attr_accessor :properties

    # Page content as an array of block objects.
    # @return [Array[Block]]
    attr_accessor :children

    # Page icon, either an emoji or external URL.
    # @return [Object]
    attr_accessor :icon

    # Page cover image as an external URL.
    # @return [ExternalFile]
    attr_accessor :cover

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['parent'] = 'parent'
      @_hash['properties'] = 'properties'
      @_hash['children'] = 'children'
      @_hash['icon'] = 'icon'
      @_hash['cover'] = 'cover'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        children
        icon
        cover
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(parent:, properties:, children: SKIP, icon: SKIP,
                   cover: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @parent = parent
      @properties = properties
      @children = children unless children == SKIP
      @icon = icon unless icon == SKIP
      @cover = cover unless cover == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      parent = Parent.from_hash(hash['parent']) if hash['parent']
      properties = hash.key?('properties') ? hash['properties'] : nil
      # Parameter is an array, so we need to iterate through it
      children = nil
      unless hash['children'].nil?
        children = []
        hash['children'].each do |structure|
          children << (Block.from_hash(structure) if structure)
        end
      end

      children = SKIP unless hash.key?('children')
      icon = hash.key?('icon') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:PagesRequestIcon), hash['icon']
      ) : SKIP
      cover = ExternalFile.from_hash(hash['cover']) if hash['cover']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PagesRequest.new(parent: parent,
                       properties: properties,
                       children: children,
                       icon: icon,
                       cover: cover,
                       additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PagesRequest | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.parent,
                                ->(val) { Parent.validate(val) },
                                is_model_hash: true) and
            APIHelper.valid_type?(value.properties,
                                  ->(val) { val.instance_of? Object })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['parent'],
                              ->(val) { Parent.validate(val) },
                              is_model_hash: true) and
          APIHelper.valid_type?(value['properties'],
                                ->(val) { val.instance_of? Object })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} parent: #{@parent}, properties: #{@properties}, children: #{@children},"\
      " icon: #{@icon}, cover: #{@cover}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} parent: #{@parent.inspect}, properties: #{@properties.inspect}, children:"\
      " #{@children.inspect}, icon: #{@icon.inspect}, cover: #{@cover.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
