# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module NotionTest
  # A Page object represents a page in a Notion workspace. Pages can exist as
  # standalone pages in a workspace or as items within a database. Each page has
  # properties, which are metadata fields defined by its parent database schema
  # or by the page itself.
  class Page < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "page" for page objects.
    # @return [Object21]
    attr_accessor :object

    # Unique identifier for the page.
    # @return [UUID | String]
    attr_accessor :id

    # Date and time when the page was created (ISO 8601).
    # @return [DateTime]
    attr_accessor :created_time

    # Date and time when the page was last edited (ISO 8601).
    # @return [DateTime]
    attr_accessor :last_edited_time

    # A partial User object containing only the object type and ID. Used in
    # created_by and last_edited_by fields.
    # @return [PartialUser]
    attr_accessor :created_by

    # A partial User object containing only the object type and ID. Used in
    # created_by and last_edited_by fields.
    # @return [PartialUser]
    attr_accessor :last_edited_by

    # Whether the page has been archived (trashed).
    # @return [TrueClass | FalseClass]
    attr_accessor :archived

    # Whether the page is in the trash.
    # @return [TrueClass | FalseClass]
    attr_accessor :in_trash

    # Page icon, either an emoji or file.
    # @return [Object]
    attr_accessor :icon

    # Page cover image.
    # @return [File]
    attr_accessor :cover

    # Property values of the page. Keys are property names or IDs.
    # @return [Object]
    attr_accessor :properties

    # A Parent object represents the parent of a page, database, or block. The
    # parent can be a workspace, page, database, or block.
    # @return [Parent]
    attr_accessor :parent

    # The URL of the page in Notion.
    # @return [String]
    attr_accessor :url

    # The public URL of the page, if the page has been published to the web.
    # Otherwise null.
    # @return [String]
    attr_accessor :public_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['object'] = 'object'
      @_hash['id'] = 'id'
      @_hash['created_time'] = 'created_time'
      @_hash['last_edited_time'] = 'last_edited_time'
      @_hash['created_by'] = 'created_by'
      @_hash['last_edited_by'] = 'last_edited_by'
      @_hash['archived'] = 'archived'
      @_hash['in_trash'] = 'in_trash'
      @_hash['icon'] = 'icon'
      @_hash['cover'] = 'cover'
      @_hash['properties'] = 'properties'
      @_hash['parent'] = 'parent'
      @_hash['url'] = 'url'
      @_hash['public_url'] = 'public_url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        in_trash
        icon
        cover
        public_url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        icon
        cover
        public_url
      ]
    end

    def initialize(object:, id:, created_time:, last_edited_time:, created_by:,
                   last_edited_by:, archived:, properties:, parent:, url:,
                   in_trash: SKIP, icon: SKIP, cover: SKIP, public_url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @object = object
      @id = id
      @created_time = created_time
      @last_edited_time = last_edited_time
      @created_by = created_by
      @last_edited_by = last_edited_by
      @archived = archived
      @in_trash = in_trash unless in_trash == SKIP
      @icon = icon unless icon == SKIP
      @cover = cover unless cover == SKIP
      @properties = properties
      @parent = parent
      @url = url
      @public_url = public_url unless public_url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      object = hash.key?('object') ? hash['object'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      created_time = if hash.key?('created_time')
                       (DateTimeHelper.from_rfc3339(hash['created_time']) if hash['created_time'])
                     end
      last_edited_time = if hash.key?('last_edited_time')
                           (DateTimeHelper.from_rfc3339(hash['last_edited_time']) if hash['last_edited_time'])
                         end
      created_by = PartialUser.from_hash(hash['created_by']) if hash['created_by']
      last_edited_by = PartialUser.from_hash(hash['last_edited_by']) if hash['last_edited_by']
      archived = hash.key?('archived') ? hash['archived'] : nil
      properties = hash.key?('properties') ? hash['properties'] : nil
      parent = Parent.from_hash(hash['parent']) if hash['parent']
      url = hash.key?('url') ? hash['url'] : nil
      in_trash = hash.key?('in_trash') ? hash['in_trash'] : SKIP
      icon = hash.key?('icon') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:PageIcon), hash['icon']
      ) : SKIP
      cover = File.from_hash(hash['cover']) if hash['cover']
      public_url = hash.key?('public_url') ? hash['public_url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Page.new(object: object,
               id: id,
               created_time: created_time,
               last_edited_time: last_edited_time,
               created_by: created_by,
               last_edited_by: last_edited_by,
               archived: archived,
               properties: properties,
               parent: parent,
               url: url,
               in_trash: in_trash,
               icon: icon,
               cover: cover,
               public_url: public_url,
               additional_properties: additional_properties)
    end

    def to_custom_created_time
      DateTimeHelper.to_rfc3339(created_time)
    end

    def to_custom_last_edited_time
      DateTimeHelper.to_rfc3339(last_edited_time)
    end

    # Validates an instance of the object from a given value.
    # @param [Page | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.object,
                                ->(val) { Object21.validate(val) }) and
            APIHelper.valid_type?(value.id,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.created_time,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.last_edited_time,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.created_by,
                                  ->(val) { PartialUser.validate(val) },
                                  is_model_hash: true) and
            APIHelper.valid_type?(value.last_edited_by,
                                  ->(val) { PartialUser.validate(val) },
                                  is_model_hash: true) and
            APIHelper.valid_type?(value.archived,
                                  ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass }) and
            APIHelper.valid_type?(value.properties,
                                  ->(val) { val.instance_of? Object }) and
            APIHelper.valid_type?(value.parent,
                                  ->(val) { Parent.validate(val) },
                                  is_model_hash: true) and
            APIHelper.valid_type?(value.url,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['object'],
                              ->(val) { Object21.validate(val) }) and
          APIHelper.valid_type?(value['id'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['created_time'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['last_edited_time'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['created_by'],
                                ->(val) { PartialUser.validate(val) },
                                is_model_hash: true) and
          APIHelper.valid_type?(value['last_edited_by'],
                                ->(val) { PartialUser.validate(val) },
                                is_model_hash: true) and
          APIHelper.valid_type?(value['archived'],
                                ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass }) and
          APIHelper.valid_type?(value['properties'],
                                ->(val) { val.instance_of? Object }) and
          APIHelper.valid_type?(value['parent'],
                                ->(val) { Parent.validate(val) },
                                is_model_hash: true) and
          APIHelper.valid_type?(value['url'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, id: #{@id}, created_time: #{@created_time},"\
      " last_edited_time: #{@last_edited_time}, created_by: #{@created_by}, last_edited_by:"\
      " #{@last_edited_by}, archived: #{@archived}, in_trash: #{@in_trash}, icon: #{@icon}, cover:"\
      " #{@cover}, properties: #{@properties}, parent: #{@parent}, url: #{@url}, public_url:"\
      " #{@public_url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, id: #{@id.inspect}, created_time:"\
      " #{@created_time.inspect}, last_edited_time: #{@last_edited_time.inspect}, created_by:"\
      " #{@created_by.inspect}, last_edited_by: #{@last_edited_by.inspect}, archived:"\
      " #{@archived.inspect}, in_trash: #{@in_trash.inspect}, icon: #{@icon.inspect}, cover:"\
      " #{@cover.inspect}, properties: #{@properties.inspect}, parent: #{@parent.inspect}, url:"\
      " #{@url.inspect}, public_url: #{@public_url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
