# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # PagesRequest1 Model.
  class PagesRequest1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Property values to update.
    # @return [Object]
    attr_accessor :properties

    # Set to true to archive (trash) the page.
    # @return [TrueClass | FalseClass]
    attr_accessor :archived

    # Page icon to set.
    # @return [Object]
    attr_accessor :icon

    # Page cover image to set or remove.
    # @return [ExternalFile]
    attr_accessor :cover

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['properties'] = 'properties'
      @_hash['archived'] = 'archived'
      @_hash['icon'] = 'icon'
      @_hash['cover'] = 'cover'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        properties
        archived
        icon
        cover
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        icon
        cover
      ]
    end

    def initialize(properties: SKIP, archived: SKIP, icon: SKIP, cover: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @properties = properties unless properties == SKIP
      @archived = archived unless archived == SKIP
      @icon = icon unless icon == SKIP
      @cover = cover unless cover == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      properties = hash.key?('properties') ? hash['properties'] : SKIP
      archived = hash.key?('archived') ? hash['archived'] : SKIP
      icon = hash.key?('icon') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:PagesRequest1Icon), hash['icon']
      ) : SKIP
      cover = ExternalFile.from_hash(hash['cover']) if hash['cover']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PagesRequest1.new(properties: properties,
                        archived: archived,
                        icon: icon,
                        cover: cover,
                        additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PagesRequest1 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} properties: #{@properties}, archived: #{@archived}, icon: #{@icon}, cover:"\
      " #{@cover}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} properties: #{@properties.inspect}, archived: #{@archived.inspect}, icon:"\
      " #{@icon.inspect}, cover: #{@cover.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
