# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # A paginated list of results returned by list and query endpoints. All
  # paginated responses follow the same structure with a results array,
  # pagination info, and object type.
  class PaginatedList < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "list" for paginated responses.
    # @return [Object]
    attr_accessor :object

    # The array of result objects for the current page.
    # @return [Array[Object]]
    attr_accessor :results

    # The cursor to use for the next page of results, or null if there are no
    # more results.
    # @return [String]
    attr_accessor :next_cursor

    # Whether there are more results available beyond this page.
    # @return [TrueClass | FalseClass]
    attr_accessor :has_more

    # The type of objects in the results array.
    # @return [String]
    attr_accessor :type

    # A unique identifier for this API request.
    # @return [String]
    attr_accessor :request_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['object'] = 'object'
      @_hash['results'] = 'results'
      @_hash['next_cursor'] = 'next_cursor'
      @_hash['has_more'] = 'has_more'
      @_hash['type'] = 'type'
      @_hash['request_id'] = 'request_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        request_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        next_cursor
      ]
    end

    def initialize(object:, results:, next_cursor:, has_more:, type: SKIP,
                   request_id: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @object = object
      @results = results
      @next_cursor = next_cursor
      @has_more = has_more
      @type = type unless type == SKIP
      @request_id = request_id unless request_id == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      object = hash.key?('object') ? hash['object'] : nil
      results = hash.key?('results') ? hash['results'] : nil
      next_cursor = hash.key?('next_cursor') ? hash['next_cursor'] : nil
      has_more = hash.key?('has_more') ? hash['has_more'] : nil
      type = hash.key?('type') ? hash['type'] : SKIP
      request_id = hash.key?('request_id') ? hash['request_id'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PaginatedList.new(object: object,
                        results: results,
                        next_cursor: next_cursor,
                        has_more: has_more,
                        type: type,
                        request_id: request_id,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, results: #{@results}, next_cursor: #{@next_cursor},"\
      " has_more: #{@has_more}, type: #{@type}, request_id: #{@request_id}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, results: #{@results.inspect}, next_cursor:"\
      " #{@next_cursor.inspect}, has_more: #{@has_more.inspect}, type: #{@type.inspect},"\
      " request_id: #{@request_id.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
