# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The parent page or block the comment belongs to.
  class Parent1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Type11]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [UUID | String]
    attr_accessor :page_id

    # TODO: Write general description for this method
    # @return [UUID | String]
    attr_accessor :block_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['page_id'] = 'page_id'
      @_hash['block_id'] = 'block_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        page_id
        block_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type: SKIP, page_id: SKIP, block_id: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type unless type == SKIP
      @page_id = page_id unless page_id == SKIP
      @block_id = block_id unless block_id == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP
      page_id = hash.key?('page_id') ? hash['page_id'] : SKIP
      block_id = hash.key?('block_id') ? hash['block_id'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Parent1.new(type: type,
                  page_id: page_id,
                  block_id: block_id,
                  additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, page_id: #{@page_id}, block_id: #{@block_id},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, page_id: #{@page_id.inspect}, block_id:"\
      " #{@block_id.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
