# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # A Parent object represents the parent of a page, database, or block. The
  # parent can be a workspace, page, database, or block.
  class Parent < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The type of parent.
    # @return [Type]
    attr_accessor :type

    # The ID of the parent database. Present when type is "database_id".
    # @return [UUID | String]
    attr_accessor :database_id

    # The ID of the parent page. Present when type is "page_id".
    # @return [UUID | String]
    attr_accessor :page_id

    # The ID of the parent block. Present when type is "block_id".
    # @return [UUID | String]
    attr_accessor :block_id

    # Always true when the parent is the workspace. Present when type is
    # "workspace".
    # @return [TrueClass | FalseClass]
    attr_accessor :workspace

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['database_id'] = 'database_id'
      @_hash['page_id'] = 'page_id'
      @_hash['block_id'] = 'block_id'
      @_hash['workspace'] = 'workspace'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        database_id
        page_id
        block_id
        workspace
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type:, database_id: SKIP, page_id: SKIP, block_id: SKIP,
                   workspace: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type
      @database_id = database_id unless database_id == SKIP
      @page_id = page_id unless page_id == SKIP
      @block_id = block_id unless block_id == SKIP
      @workspace = workspace unless workspace == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : nil
      database_id = hash.key?('database_id') ? hash['database_id'] : SKIP
      page_id = hash.key?('page_id') ? hash['page_id'] : SKIP
      block_id = hash.key?('block_id') ? hash['block_id'] : SKIP
      workspace = hash.key?('workspace') ? hash['workspace'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Parent.new(type: type,
                 database_id: database_id,
                 page_id: page_id,
                 block_id: block_id,
                 workspace: workspace,
                 additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Parent | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.type,
                                     ->(val) { Type.validate(val) })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['type'],
                            ->(val) { Type.validate(val) })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, database_id: #{@database_id}, page_id: #{@page_id},"\
      " block_id: #{@block_id}, workspace: #{@workspace}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, database_id: #{@database_id.inspect}, page_id:"\
      " #{@page_id.inspect}, block_id: #{@block_id.inspect}, workspace: #{@workspace.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
