# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # A partial User object containing only the object type and ID. Used in
  # created_by and last_edited_by fields.
  class PartialUser < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "user".
    # @return [Object2]
    attr_accessor :object

    # Unique identifier for the user.
    # @return [UUID | String]
    attr_accessor :id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['object'] = 'object'
      @_hash['id'] = 'id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(object:, id:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @object = object
      @id = id
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      object = hash.key?('object') ? hash['object'] : nil
      id = hash.key?('id') ? hash['id'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PartialUser.new(object: object,
                      id: id,
                      additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PartialUser | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.object,
                                ->(val) { Object2.validate(val) }) and
            APIHelper.valid_type?(value.id,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['object'],
                              ->(val) { Object2.validate(val) }) and
          APIHelper.valid_type?(value['id'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, id: #{@id}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, id: #{@id.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
