# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Must be "object".
  class Property
    PROPERTY = [
      # TODO: Write general description for OBJECT
      OBJECT = 'object'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PROPERTY.include?(value)
    end

    def self.from_value(value, default_value = OBJECT)
      return default_value if value.nil?

      default_value
    end
  end
end
