# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # A Property Schema object defines a database property's configuration
  # including its type and type-specific settings. Common property types include
  # title, rich_text, number, select, multi_select, date, people, files,
  # checkbox, url, email, phone_number, formula, relation, rollup, created_time,
  # created_by, last_edited_time, last_edited_by, and status.
  class PropertySchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The ID of the property.
    # @return [String]
    attr_accessor :id

    # The name of the property.
    # @return [String]
    attr_accessor :name

    # The type of property.
    # @return [Type31]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        name
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, name: SKIP, type: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @id = id unless id == SKIP
      @name = name unless name == SKIP
      @type = type unless type == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PropertySchema.new(id: id,
                         name: name,
                         type: type,
                         additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PropertySchema | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, name: #{@name}, type: #{@type}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, name: #{@name.inspect}, type: #{@type.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
