# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # A Rich Text object represents styled text content in Notion. Rich text can
  # include annotations like bold, italic, and color, as well as links and
  # mentions of other Notion objects.
  class RichText < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The type of this rich text object.
    # @return [Type2]
    attr_accessor :type

    # Text content and optional link. Present when type is "text".
    # @return [Text]
    attr_accessor :text

    # Mention content. Present when type is "mention". Can reference users,
    # pages, databases, dates, or link previews.
    # @return [Object]
    attr_accessor :mention

    # Equation content in KaTeX format. Present when type is "equation".
    # @return [Equation]
    attr_accessor :equation

    # Styling annotations applied to the text.
    # @return [Annotations]
    attr_accessor :annotations

    # The plain text content without annotations.
    # @return [String]
    attr_accessor :plain_text

    # The URL of any link in the text, or null.
    # @return [String]
    attr_accessor :href

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['text'] = 'text'
      @_hash['mention'] = 'mention'
      @_hash['equation'] = 'equation'
      @_hash['annotations'] = 'annotations'
      @_hash['plain_text'] = 'plain_text'
      @_hash['href'] = 'href'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        text
        mention
        equation
        annotations
        href
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        href
      ]
    end

    def initialize(type:, plain_text:, text: SKIP, mention: SKIP,
                   equation: SKIP, annotations: SKIP, href: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type
      @text = text unless text == SKIP
      @mention = mention unless mention == SKIP
      @equation = equation unless equation == SKIP
      @annotations = annotations unless annotations == SKIP
      @plain_text = plain_text
      @href = href unless href == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : nil
      plain_text = hash.key?('plain_text') ? hash['plain_text'] : nil
      text = Text.from_hash(hash['text']) if hash['text']
      mention = hash.key?('mention') ? hash['mention'] : SKIP
      equation = Equation.from_hash(hash['equation']) if hash['equation']
      annotations = Annotations.from_hash(hash['annotations']) if hash['annotations']
      href = hash.key?('href') ? hash['href'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      RichText.new(type: type,
                   plain_text: plain_text,
                   text: text,
                   mention: mention,
                   equation: equation,
                   annotations: annotations,
                   href: href,
                   additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [RichText | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.type,
                                ->(val) { Type2.validate(val) }) and
            APIHelper.valid_type?(value.plain_text,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['type'],
                              ->(val) { Type2.validate(val) }) and
          APIHelper.valid_type?(value['plain_text'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, text: #{@text}, mention: #{@mention}, equation:"\
      " #{@equation}, annotations: #{@annotations}, plain_text: #{@plain_text}, href: #{@href},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, text: #{@text.inspect}, mention:"\
      " #{@mention.inspect}, equation: #{@equation.inspect}, annotations: #{@annotations.inspect},"\
      " plain_text: #{@plain_text.inspect}, href: #{@href.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
