# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # SearchRequest Model.
  class SearchRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The text to search for in page and database titles. If omitted, returns
    # all pages and databases.
    # @return [String]
    attr_accessor :query

    # Filter conditions. Currently only supports filtering by object type (page
    # or database).
    # @return [Filter]
    attr_accessor :filter

    # Sort conditions for the results.
    # @return [Sort1]
    attr_accessor :sort

    # Pagination cursor to continue fetching results.
    # @return [String]
    attr_accessor :start_cursor

    # Maximum number of results to return (max 100).
    # @return [Integer]
    attr_accessor :page_size

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['query'] = 'query'
      @_hash['filter'] = 'filter'
      @_hash['sort'] = 'sort'
      @_hash['start_cursor'] = 'start_cursor'
      @_hash['page_size'] = 'page_size'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        query
        filter
        sort
        start_cursor
        page_size
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(query: SKIP, filter: SKIP, sort: SKIP, start_cursor: SKIP,
                   page_size: 100, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @query = query unless query == SKIP
      @filter = filter unless filter == SKIP
      @sort = sort unless sort == SKIP
      @start_cursor = start_cursor unless start_cursor == SKIP
      @page_size = page_size unless page_size == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      query = hash.key?('query') ? hash['query'] : SKIP
      filter = Filter.from_hash(hash['filter']) if hash['filter']
      sort = Sort1.from_hash(hash['sort']) if hash['sort']
      start_cursor = hash.key?('start_cursor') ? hash['start_cursor'] : SKIP
      page_size = hash['page_size'] ||= 100

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      SearchRequest.new(query: query,
                        filter: filter,
                        sort: sort,
                        start_cursor: start_cursor,
                        page_size: page_size,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} query: #{@query}, filter: #{@filter}, sort: #{@sort}, start_cursor:"\
      " #{@start_cursor}, page_size: #{@page_size}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} query: #{@query.inspect}, filter: #{@filter.inspect}, sort:"\
      " #{@sort.inspect}, start_cursor: #{@start_cursor.inspect}, page_size:"\
      " #{@page_size.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
