# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Sort Model.
  class Sort < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of the property to sort by.
    # @return [String]
    attr_accessor :property

    # The timestamp to sort by. Possible values are created_time or
    # last_edited_time.
    # @return [Timestamp]
    attr_accessor :timestamp

    # The sort direction.
    # @return [Direction]
    attr_accessor :direction

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['property'] = 'property'
      @_hash['timestamp'] = 'timestamp'
      @_hash['direction'] = 'direction'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        property
        timestamp
        direction
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(property: SKIP, timestamp: SKIP, direction: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @property = property unless property == SKIP
      @timestamp = timestamp unless timestamp == SKIP
      @direction = direction unless direction == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      property = hash.key?('property') ? hash['property'] : SKIP
      timestamp = hash.key?('timestamp') ? hash['timestamp'] : SKIP
      direction = hash.key?('direction') ? hash['direction'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Sort.new(property: property,
               timestamp: timestamp,
               direction: direction,
               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} property: #{@property}, timestamp: #{@timestamp}, direction: #{@direction},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} property: #{@property.inspect}, timestamp: #{@timestamp.inspect},"\
      " direction: #{@direction.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
