# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Sort conditions for the results.
  class Sort1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The sort direction.
    # @return [Direction]
    attr_accessor :direction

    # The timestamp to sort by.
    # @return [Timestamp1]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['direction'] = 'direction'
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        direction
        timestamp
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(direction: SKIP, timestamp: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @direction = direction unless direction == SKIP
      @timestamp = timestamp unless timestamp == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      direction = hash.key?('direction') ? hash['direction'] : SKIP
      timestamp = hash.key?('timestamp') ? hash['timestamp'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Sort1.new(direction: direction,
                timestamp: timestamp,
                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} direction: #{@direction}, timestamp: #{@timestamp}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} direction: #{@direction.inspect}, timestamp: #{@timestamp.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
