# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Text content and optional link. Present when type is "text".
  class Text < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The actual text content.
    # @return [String]
    attr_accessor :content

    # Optional link within the text.
    # @return [Link]
    attr_accessor :link

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['content'] = 'content'
      @_hash['link'] = 'link'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        content
        link
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        link
      ]
    end

    def initialize(content: SKIP, link: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @content = content unless content == SKIP
      @link = link unless link == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      content = hash.key?('content') ? hash['content'] : SKIP
      link = Link.from_hash(hash['link']) if hash['link']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Text.new(content: content,
               link: link,
               additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Text | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} content: #{@content}, link: #{@link}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} content: #{@content.inspect}, link: #{@link.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
