# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The timestamp to sort by.
  class Timestamp1
    TIMESTAMP1 = [
      # TODO: Write general description for LAST_EDITED_TIME
      LAST_EDITED_TIME = 'last_edited_time'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TIMESTAMP1.include?(value)
    end

    def self.from_value(value, default_value = LAST_EDITED_TIME)
      return default_value if value.nil?

      default_value
    end
  end
end
