# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The timestamp to sort by. Possible values are created_time or
  # last_edited_time.
  class Timestamp
    TIMESTAMP = [
      # TODO: Write general description for CREATED_TIME
      CREATED_TIME = 'created_time'.freeze,

      # TODO: Write general description for LAST_EDITED_TIME
      LAST_EDITED_TIME = 'last_edited_time'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TIMESTAMP.include?(value)
    end

    def self.from_value(value, default_value = CREATED_TIME)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'created_time' then CREATED_TIME
      when 'last_edited_time' then LAST_EDITED_TIME
      else
        default_value
      end
    end
  end
end
