# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "emoji".
  class Type3
    TYPE3 = [
      # TODO: Write general description for EMOJI
      EMOJI = 'emoji'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE3.include?(value)
    end

    def self.from_value(value, default_value = EMOJI)
      return default_value if value.nil?

      default_value
    end
  end
end
