# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Type11.
  class Type11
    TYPE11 = [
      # TODO: Write general description for PAGE_ID
      PAGE_ID = 'page_id'.freeze,

      # TODO: Write general description for BLOCK_ID
      BLOCK_ID = 'block_id'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE11.include?(value)
    end

    def self.from_value(value, default_value = PAGE_ID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'page_id' then PAGE_ID
      when 'block_id' then BLOCK_ID
      else
        default_value
      end
    end
  end
end
