# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The type of user. "person" for human workspace members, "bot" for API
  # integrations.
  class Type4
    TYPE4 = [
      # TODO: Write general description for PERSON
      PERSON = 'person'.freeze,

      # TODO: Write general description for BOT
      BOT = 'bot'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE4.include?(value)
    end

    def self.from_value(value, default_value = PERSON)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'person' then PERSON
      when 'bot' then BOT
      else
        default_value
      end
    end
  end
end
