# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The type of parent.
  class Type
    TYPE = [
      # TODO: Write general description for DATABASE_ID
      DATABASE_ID = 'database_id'.freeze,

      # TODO: Write general description for PAGE_ID
      PAGE_ID = 'page_id'.freeze,

      # TODO: Write general description for BLOCK_ID
      BLOCK_ID = 'block_id'.freeze,

      # TODO: Write general description for WORKSPACE
      WORKSPACE = 'workspace'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE.include?(value)
    end

    def self.from_value(value, default_value = DATABASE_ID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'database_id' then DATABASE_ID
      when 'page_id' then PAGE_ID
      when 'block_id' then BLOCK_ID
      when 'workspace' then WORKSPACE
      else
        default_value
      end
    end
  end
end
