# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The type of this rich text object.
  class Type2
    TYPE2 = [
      # TODO: Write general description for TEXT
      TEXT = 'text'.freeze,

      # TODO: Write general description for MENTION
      MENTION = 'mention'.freeze,

      # TODO: Write general description for EQUATION
      EQUATION = 'equation'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE2.include?(value)
    end

    def self.from_value(value, default_value = TEXT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'text' then TEXT
      when 'mention' then MENTION
      when 'equation' then EQUATION
      else
        default_value
      end
    end
  end
end
