# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The type of file hosting.
  class Type21
    TYPE21 = [
      # TODO: Write general description for FILE
      FILE = 'file'.freeze,

      # TODO: Write general description for EXTERNAL
      EXTERNAL = 'external'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE21.include?(value)
    end

    def self.from_value(value, default_value = FILE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'file' then FILE
      when 'external' then EXTERNAL
      else
        default_value
      end
    end
  end
end
