# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The type of property.
  class Type31
    TYPE31 = [
      # TODO: Write general description for TITLE
      TITLE = 'title'.freeze,

      # TODO: Write general description for RICH_TEXT
      RICH_TEXT = 'rich_text'.freeze,

      # TODO: Write general description for NUMBER
      NUMBER = 'number'.freeze,

      # TODO: Write general description for SELECT
      SELECT = 'select'.freeze,

      # TODO: Write general description for MULTI_SELECT
      MULTI_SELECT = 'multi_select'.freeze,

      # TODO: Write general description for DATE
      DATE = 'date'.freeze,

      # TODO: Write general description for PEOPLE
      PEOPLE = 'people'.freeze,

      # TODO: Write general description for FILES
      FILES = 'files'.freeze,

      # TODO: Write general description for CHECKBOX
      CHECKBOX = 'checkbox'.freeze,

      # TODO: Write general description for URL
      URL = 'url'.freeze,

      # TODO: Write general description for EMAIL
      EMAIL = 'email'.freeze,

      # TODO: Write general description for PHONE_NUMBER
      PHONE_NUMBER = 'phone_number'.freeze,

      # TODO: Write general description for FORMULA
      FORMULA = 'formula'.freeze,

      # TODO: Write general description for RELATION
      RELATION = 'relation'.freeze,

      # TODO: Write general description for ROLLUP
      ROLLUP = 'rollup'.freeze,

      # TODO: Write general description for CREATED_TIME
      CREATED_TIME = 'created_time'.freeze,

      # TODO: Write general description for CREATED_BY
      CREATED_BY = 'created_by'.freeze,

      # TODO: Write general description for LAST_EDITED_TIME
      LAST_EDITED_TIME = 'last_edited_time'.freeze,

      # TODO: Write general description for LAST_EDITED_BY
      LAST_EDITED_BY = 'last_edited_by'.freeze,

      # TODO: Write general description for STATUS
      STATUS = 'status'.freeze,

      # TODO: Write general description for UNIQUE_ID
      UNIQUE_ID = 'unique_id'.freeze,

      # TODO: Write general description for VERIFICATION
      VERIFICATION = 'verification'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE31.include?(value)
    end

    def self.from_value(value, default_value = TITLE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'title' then TITLE
      when 'rich_text' then RICH_TEXT
      when 'number' then NUMBER
      when 'select' then SELECT
      when 'multi_select' then MULTI_SELECT
      when 'date' then DATE
      when 'people' then PEOPLE
      when 'files' then FILES
      when 'checkbox' then CHECKBOX
      when 'url' then URL
      when 'email' then EMAIL
      when 'phone_number' then PHONE_NUMBER
      when 'formula' then FORMULA
      when 'relation' then RELATION
      when 'rollup' then ROLLUP
      when 'created_time' then CREATED_TIME
      when 'created_by' then CREATED_BY
      when 'last_edited_time' then LAST_EDITED_TIME
      when 'last_edited_by' then LAST_EDITED_BY
      when 'status' then STATUS
      when 'unique_id' then UNIQUE_ID
      when 'verification' then VERIFICATION
      else
        default_value
      end
    end
  end
end
