# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Always "external".
  class Type5
    TYPE5 = [
      # TODO: Write general description for EXTERNAL
      EXTERNAL = 'external'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE5.include?(value)
    end

    def self.from_value(value, default_value = EXTERNAL)
      return default_value if value.nil?

      default_value
    end
  end
end
