# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Type12.
  class Type12
    TYPE12 = [
      # TODO: Write general description for WORKSPACE
      WORKSPACE = 'workspace'.freeze,

      # TODO: Write general description for USER
      USER = 'user'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE12.include?(value)
    end

    def self.from_value(value, default_value = WORKSPACE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'workspace' then WORKSPACE
      when 'user' then USER
      else
        default_value
      end
    end
  end
end
