# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The type of block. Determines which type-specific content field is present.
  # Common types include paragraph, heading_1, heading_2, heading_3,
  # bulleted_list_item, numbered_list_item, to_do, toggle, code, image, divider,
  # table, and many more.
  class Type1
    TYPE1 = [
      # TODO: Write general description for PARAGRAPH
      PARAGRAPH = 'paragraph'.freeze,

      # TODO: Write general description for HEADING_1
      HEADING_1 = 'heading_1'.freeze,

      # TODO: Write general description for HEADING_2
      HEADING_2 = 'heading_2'.freeze,

      # TODO: Write general description for HEADING_3
      HEADING_3 = 'heading_3'.freeze,

      # TODO: Write general description for BULLETED_LIST_ITEM
      BULLETED_LIST_ITEM = 'bulleted_list_item'.freeze,

      # TODO: Write general description for NUMBERED_LIST_ITEM
      NUMBERED_LIST_ITEM = 'numbered_list_item'.freeze,

      # TODO: Write general description for TO_DO
      TO_DO = 'to_do'.freeze,

      # TODO: Write general description for TOGGLE
      TOGGLE = 'toggle'.freeze,

      # TODO: Write general description for CHILD_PAGE
      CHILD_PAGE = 'child_page'.freeze,

      # TODO: Write general description for CHILD_DATABASE
      CHILD_DATABASE = 'child_database'.freeze,

      # TODO: Write general description for EMBED
      EMBED = 'embed'.freeze,

      # TODO: Write general description for IMAGE
      IMAGE = 'image'.freeze,

      # TODO: Write general description for VIDEO
      VIDEO = 'video'.freeze,

      # TODO: Write general description for FILE
      FILE = 'file'.freeze,

      # TODO: Write general description for PDF
      PDF = 'pdf'.freeze,

      # TODO: Write general description for BOOKMARK
      BOOKMARK = 'bookmark'.freeze,

      # TODO: Write general description for CALLOUT
      CALLOUT = 'callout'.freeze,

      # TODO: Write general description for QUOTE
      QUOTE = 'quote'.freeze,

      # TODO: Write general description for EQUATION
      EQUATION = 'equation'.freeze,

      # TODO: Write general description for DIVIDER
      DIVIDER = 'divider'.freeze,

      # TODO: Write general description for TABLE_OF_CONTENTS
      TABLE_OF_CONTENTS = 'table_of_contents'.freeze,

      # TODO: Write general description for COLUMN_LIST
      COLUMN_LIST = 'column_list'.freeze,

      # TODO: Write general description for COLUMN
      COLUMN = 'column'.freeze,

      # TODO: Write general description for LINK_PREVIEW
      LINK_PREVIEW = 'link_preview'.freeze,

      # TODO: Write general description for SYNCED_BLOCK
      SYNCED_BLOCK = 'synced_block'.freeze,

      # TODO: Write general description for TEMPLATE
      TEMPLATE = 'template'.freeze,

      # TODO: Write general description for LINK_TO_PAGE
      LINK_TO_PAGE = 'link_to_page'.freeze,

      # TODO: Write general description for TABLE
      TABLE = 'table'.freeze,

      # TODO: Write general description for TABLE_ROW
      TABLE_ROW = 'table_row'.freeze,

      # TODO: Write general description for CODE
      CODE = 'code'.freeze,

      # TODO: Write general description for AUDIO
      AUDIO = 'audio'.freeze,

      # TODO: Write general description for BREADCRUMB
      BREADCRUMB = 'breadcrumb'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE1.include?(value)
    end

    def self.from_value(value, default_value = PARAGRAPH)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'paragraph' then PARAGRAPH
      when 'heading_1' then HEADING_1
      when 'heading_2' then HEADING_2
      when 'heading_3' then HEADING_3
      when 'bulleted_list_item' then BULLETED_LIST_ITEM
      when 'numbered_list_item' then NUMBERED_LIST_ITEM
      when 'to_do' then TO_DO
      when 'toggle' then TOGGLE
      when 'child_page' then CHILD_PAGE
      when 'child_database' then CHILD_DATABASE
      when 'embed' then EMBED
      when 'image' then IMAGE
      when 'video' then VIDEO
      when 'file' then FILE
      when 'pdf' then PDF
      when 'bookmark' then BOOKMARK
      when 'callout' then CALLOUT
      when 'quote' then QUOTE
      when 'equation' then EQUATION
      when 'divider' then DIVIDER
      when 'table_of_contents' then TABLE_OF_CONTENTS
      when 'column_list' then COLUMN_LIST
      when 'column' then COLUMN
      when 'link_preview' then LINK_PREVIEW
      when 'synced_block' then SYNCED_BLOCK
      when 'template' then TEMPLATE
      when 'link_to_page' then LINK_TO_PAGE
      when 'table' then TABLE
      when 'table_row' then TABLE_ROW
      when 'code' then CODE
      when 'audio' then AUDIO
      when 'breadcrumb' then BREADCRUMB
      else
        default_value
      end
    end
  end
end
