# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # A User object represents a user in a Notion workspace. Users can be either
  # people (human workspace members) or bots (API integrations). User objects
  # include identifying information such as name, email, and avatar URL.
  class User < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Always "user" for user objects.
    # @return [Object2]
    attr_accessor :object

    # Unique identifier for the user.
    # @return [UUID | String]
    attr_accessor :id

    # The type of user. "person" for human workspace members, "bot" for API
    # integrations.
    # @return [Type4]
    attr_accessor :type

    # Display name of the user.
    # @return [String]
    attr_accessor :name

    # URL of the user's avatar image.
    # @return [String]
    attr_accessor :avatar_url

    # Person-specific information. Only present when type is "person".
    # @return [Person]
    attr_accessor :person

    # Bot-specific information. Only present when type is "bot".
    # @return [Bot]
    attr_accessor :bot

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['object'] = 'object'
      @_hash['id'] = 'id'
      @_hash['type'] = 'type'
      @_hash['name'] = 'name'
      @_hash['avatar_url'] = 'avatar_url'
      @_hash['person'] = 'person'
      @_hash['bot'] = 'bot'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        name
        avatar_url
        person
        bot
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        name
        avatar_url
      ]
    end

    def initialize(object:, id:, type: SKIP, name: SKIP, avatar_url: SKIP,
                   person: SKIP, bot: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @object = object
      @id = id
      @type = type unless type == SKIP
      @name = name unless name == SKIP
      @avatar_url = avatar_url unless avatar_url == SKIP
      @person = person unless person == SKIP
      @bot = bot unless bot == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      object = hash.key?('object') ? hash['object'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      type = hash.key?('type') ? hash['type'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      avatar_url = hash.key?('avatar_url') ? hash['avatar_url'] : SKIP
      person = Person.from_hash(hash['person']) if hash['person']
      bot = Bot.from_hash(hash['bot']) if hash['bot']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      User.new(object: object,
               id: id,
               type: type,
               name: name,
               avatar_url: avatar_url,
               person: person,
               bot: bot,
               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, id: #{@id}, type: #{@type}, name: #{@name}, avatar_url:"\
      " #{@avatar_url}, person: #{@person}, bot: #{@bot}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, id: #{@id.inspect}, type: #{@type.inspect},"\
      " name: #{@name.inspect}, avatar_url: #{@avatar_url.inspect}, person: #{@person.inspect},"\
      " bot: #{@bot.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
