# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The type of object to filter by.
  class Value
    VALUE = [
      # TODO: Write general description for PAGE
      PAGE = 'page'.freeze,

      # TODO: Write general description for DATABASE
      DATABASE = 'database'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      VALUE.include?(value)
    end

    def self.from_value(value, default_value = PAGE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'page' then PAGE
      when 'database' then DATABASE
      else
        default_value
      end
    end
  end
end
