# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # CommentsApi
  class CommentsApi < BaseApi
    # Retrieves a list of unresolved comments from a page or block. Requires the
    # integration to have read comment capabilities.
    # @param [String] notion_version Required parameter: The version of the
    # Notion API to use. The current version is 2022-06-28. This header is
    # required for all API requests.
    # @param [UUID | String] block_id Required parameter: The ID of the block or
    # page to retrieve comments for.
    # @param [String] start_cursor Optional parameter: Pagination cursor to
    # continue fetching results.
    # @param [Integer] page_size Optional parameter: Maximum number of comments
    # to return (max 100).
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_comments(notion_version,
                      block_id,
                      start_cursor: nil,
                      page_size: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/comments',
                                     Server::DEFAULT)
                   .header_param(new_parameter(notion_version, key: 'Notion-Version')
                                  .is_required(true))
                   .query_param(new_parameter(block_id, key: 'block_id')
                                 .is_required(true))
                   .query_param(new_parameter(start_cursor, key: 'start_cursor'))
                   .query_param(new_parameter(page_size, key: 'page_size'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(PaginatedList.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'The bearer token is missing, invalid, or the integration lacks'\
                                  ' access.',
                                 ErrorException)
                    .local_error('404',
                                 'The requested resource does not exist or the integration lacks'\
                                  ' access to it.',
                                 ErrorException)
                    .local_error('429',
                                 'The request has been rate limited. Notion enforces rate limits'\
                                  ' of 3 requests per second for integrations. Retry after the'\
                                  ' specified delay.',
                                 ErrorException))
        .execute
    end

    # Creates a comment on a page or in an existing discussion thread. The
    # integration must have comment capabilities to use this endpoint.
    # @param [String] notion_version Required parameter: The version of the
    # Notion API to use. The current version is 2022-06-28. This header is
    # required for all API requests.
    # @param [CommentsRequest] body Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_comment(notion_version,
                       body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/comments',
                                     Server::DEFAULT)
                   .header_param(new_parameter(notion_version, key: 'Notion-Version')
                                  .is_required(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Comment.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'The request was invalid or malformed.',
                                 ErrorException)
                    .local_error('401',
                                 'The bearer token is missing, invalid, or the integration lacks'\
                                  ' access.',
                                 ErrorException)
                    .local_error('404',
                                 'The requested resource does not exist or the integration lacks'\
                                  ' access to it.',
                                 ErrorException)
                    .local_error('429',
                                 'The request has been rate limited. Notion enforces rate limits'\
                                  ' of 3 requests per second for integrations. Retry after the'\
                                  ' specified delay.',
                                 ErrorException))
        .execute
    end
  end
end
