# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # SearchApi
  class SearchApi < BaseApi
    # Searches all parent or child pages and databases that have been shared
    # with an integration. Returns results based on the query, filter, and sort
    # parameters. Results are sorted by relevance by default but can be sorted
    # by last_edited_time. The search indexing may not be immediate, so recently
    # created or updated objects may not appear right away.
    # @param [String] notion_version Required parameter: The version of the
    # Notion API to use. The current version is 2022-06-28. This header is
    # required for all API requests.
    # @param [SearchRequest] body Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def search(notion_version,
               body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/search',
                                     Server::DEFAULT)
                   .header_param(new_parameter(notion_version, key: 'Notion-Version')
                                  .is_required(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(PaginatedList.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'The request was invalid or malformed.',
                                 ErrorException)
                    .local_error('401',
                                 'The bearer token is missing, invalid, or the integration lacks'\
                                  ' access.',
                                 ErrorException)
                    .local_error('429',
                                 'The request has been rate limited. Notion enforces rate limits'\
                                  ' of 3 requests per second for integrations. Retry after the'\
                                  ' specified delay.',
                                 ErrorException))
        .execute
    end
  end
end
