# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # The `UnionTypeLookUp` class serves as a utility class for
  # storing and managing type combinator templates. It acts as a container for the templates
  # used in handling various oneof/anyof instances within the sdk.
  class UnionTypeLookUp
    include CoreLibrary
    # rubocop:disable Lint/RedundantCopDisableDirective, Style/HashSyntax, Layout/FirstArgumentIndentation
    def self.union_types
      {
        :DatabaseIcon => OneOf.new(
          [
            LeafType.new(Emoji),
            LeafType.new(File)
          ],
          UnionTypeContext.new(
            is_optional: true,
            is_nullable: true
          )
        ),

        :DatabasesRequestIcon => OneOf.new(
          [
            LeafType.new(Emoji),
            LeafType.new(ExternalFile)
          ],
          UnionTypeContext.new(
            is_optional: true
          )
        ),

        :DatabasesRequest1Icon => OneOf.new(
          [
            LeafType.new(Emoji),
            LeafType.new(ExternalFile)
          ],
          UnionTypeContext.new(
            is_optional: true,
            is_nullable: true
          )
        ),

        :PageIcon => OneOf.new(
          [
            LeafType.new(Emoji),
            LeafType.new(File)
          ],
          UnionTypeContext.new(
            is_optional: true,
            is_nullable: true
          )
        ),

        :PagesRequestIcon => OneOf.new(
          [
            LeafType.new(Emoji),
            LeafType.new(ExternalFile)
          ],
          UnionTypeContext.new(
            is_optional: true
          )
        ),

        :PagesRequest1Icon => OneOf.new(
          [
            LeafType.new(Emoji),
            LeafType.new(ExternalFile)
          ],
          UnionTypeContext.new(
            is_optional: true,
            is_nullable: true
          )
        )
      }
    end
    # rubocop:enable Lint/RedundantCopDisableDirective, Style/HashSyntax, Layout/FirstArgumentIndentation

    def self.get(name)
      UnionTypeLookUp.union_types[name]
    end
  end
end
