# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
