# notion_test
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module NotionTest
  # An error response from the Notion API.
  class ErrorException < APIException
    SKIP = Object.new
    private_constant :SKIP

    # Always "error" for error responses.
    # @return [Object3]
    attr_accessor :object

    # The HTTP status code.
    # @return [Integer]
    attr_accessor :status

    # A machine-readable error code. Common codes include invalid_json,
    # invalid_request_url, invalid_request, validation_error, missing_version,
    # unauthorized, restricted_resource, object_not_found, conflict_error,
    # rate_limited, internal_server_error, service_unavailable, and
    # database_connection_unavailable.
    # @return [String]
    attr_accessor :code

    # A human-readable error message.
    # @return [String]
    attr_accessor :message

    # A unique identifier for the failed request.
    # @return [String]
    attr_accessor :request_id

    # The constructor.
    # @param [String] reason The reason for raising an exception.
    # @param [HttpResponse] response The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] hash The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      return nil unless hash

      @object = hash.key?('object') ? hash['object'] : nil
      @status = hash.key?('status') ? hash['status'] : nil
      @code = hash.key?('code') ? hash['code'] : nil
      @message = hash.key?('message') ? hash['message'] : nil
      @request_id = hash.key?('request_id') ? hash['request_id'] : SKIP
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object}, status: #{@status}, code: #{@code}, message:"\
      " #{@message}, request_id: #{@request_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} object: #{@object.inspect}, status: #{@status.inspect}, code:"\
      " #{@code.inspect}, message: #{@message.inspect}, request_id: #{@request_id.inspect}>"
    end
  end
end
